on:
    push:
        paths:
            - .github/workflows/test-custom-docker-action.yml
jobs:
    hello_world_job:
        runs-on: ubuntu-latest
        name: A job to say hello
        steps:
            - name: Hello World action step
              id: hello
              uses: djoksa4/actions-hello-world-docker@v1
              with:
                who-to-greet: 'Martha'
            
            - name: Get the output time
              run: echo "The time was ${{ steps.hello.outputs.time }}"