on:
    push:
        paths:
            - .github/workflows/test-custom-composite-action.yml
jobs:
    hello_world_job:
        runs-on: ubuntu-latest
        name: A job to say hello
        steps:
            - uses: djoksa4/actions-hello-world-composite@v1
              id: foo
              with:
                who-to-greet: 'Kriss'
                
            - run: echo random-number "$RANDOM_NUMBER"
              shell: bash
              env:
                RANDOM_NUMBER: ${{ steps.foo.outputs.random-number }}